name: Ghillie Suit
jquery_js: js/jquery-1.7.1.min.js
# exclude:

safe: false
# auto: true
server: false
server_port: 4000
baseurl: /
url: http://localhost:4000

source: .
# destination: ./_site
# plugins:     ./_plugins

future: true
lsi: false
pygments: true
permalink: /:categories/:title.html